//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileBucket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cloud
    {
        public int id { get; set; }
        public int root { get; set; }
        public int parent { get; set; }
        public int child { get; set; }
        public string name { get; set; }
        public int type { get; set; }
        public int share { get; set; }
        public int size { get; set; }
        public string time { get; set; }
    }
}
